name: update_data
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'LICENSE'
  schedule:
    - cron: '30 06 * * 5'
  workflow_dispatch:
permissions:
      contents: write
      pull-requests: write
      repository-projects: write

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update data
      run: sh update_data.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
    # - uses: EndBug/add-and-commit@v9
    #   with:
    #     author_name: Github Actions
    #     author_email: actions@github.com
    #     committer_email: actions@github.com
    - name: Flash CDN
      run: |
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/trackerslist.txt.xz &&
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/trackerslist.txt.xz.sha256sum
